package it.keyover.trsserver.entity;
// Generated 1-gen-2019 20.40.21 by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserPreferences generated by hbm2java
 */
@Entity
@Table(name = "user_preferences", catalog = "irdatabase")
public class UserPreferences implements java.io.Serializable {

	private Integer id;
	private Users users;
	private String preference;

	public UserPreferences() {
	}

	public UserPreferences(Users users, String preference) {
		this.users = users;
		this.preference = preference;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userId", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "preference", nullable = false, length = 50)
	public String getPreference() {
		return this.preference;
	}

	public void setPreference(String preference) {
		this.preference = preference;
	}

}
